#ifndef COMMAND_DOCUMENT_COMMANDS_COMMON_HPP
#define COMMAND_DOCUMENT_COMMANDS_COMMON_HPP

enum class CommandName
{
    DELETE_ITEM_COMMAND = 0,
    INSERT_ITEM_COMMAND,
    REPLACE_ITEM_COMMAND,
    SET_TITLE_COMMAND
};

#endif
